name: Terraform Validate

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.5  # Specify your required Terraform version

      - name: Check Terraform Version
        run: terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate